SELECT * FROM SALES GROUP BY ROLLUP(QTY);

SELECT *, max(QTY) over (PARTITION BY Product ORDER BY SalesRep RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM SALES;

select * from (SELECT customer_id,c_mktsegment
FROM sa.CUSTOMER as a cross join sa.ORDERS as b
WHERE a.c_custkey=b.o_custkey)
as c;

select elementtyp1_.ID as ID, elementtyp1_.VERSION as VERSION, elementtyp1_.name as name, leafelemen0_.String01 as x0_0_, leafelemen0__1_.ORIGINAL_ID as x1_0_, elementtyp1_.ID as x2_0_, leafelemen0__1_.UNIQUE_NAME as x3_0_ from DICT_LEAF_ELEMENTS leafelemen0_ inner join DICT_ELEMENTS leafelemen0__1_ on leafelemen0_.ELEMENT_ID=leafelemen0__1_.ID, DICT_ELEMENT_TYPES elementtyp1_ where leafelemen0_.TYPE_ID=elementtyp1_.ID and (((leafelemen0_.TYPE_ID=? )AND(((leafelemen0_.String01 LIKE ? ESCAPE '\' )OR(leafelemen0_.String01 LIKE ? ESCAPE '\' )OR(leafelemen0_.String01 LIKE ? ESCAPE '\' )OR(leafelemen0_.String01 LIKE ? ESCAPE '\' ))AND(lower(leafelemen0_.String01)=? )AND(leafelemen0_.String01 is not null ))and(String01 is not null ))and(leafelemen0__1_.ACTIVE_TO>? )and(leafelemen0__1_.ACTIVE_FROM<=? ));

insert into HEART_BEAT_RECORD (timestamp) values (?);

insert into policy_activity_log (id, time, month_nb, day_nb, host_id, user_id, application_id, application_name, action, fromresourcename, fromresourcesize, fromresourceownerid, fromresourcecreateddate, fromresourcemodifieddate, toresourcename, policy_id, policy_decision, decision_request_id, host_name, host_ip, user_name, log_level) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

insert into RPA_LOG (id,time, request_date_time, month_nb, week_nb, day_nb, hour_nb, minute_nb ,host_id,host_ip,host_name,user_id,user_name,user_sid,application_id,application_name,action,policy_id,policy_name,policy_fullname,policy_decision,decision_request_id,log_level,from_resource_name,from_resource_prefix,from_resource_path,from_resource_short_name,from_resource_size,from_resource_owner_id,from_resource_created_date,from_resource_modified_date,to_resource_name, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8, attr9, attr10, attr11, attr12, attr13, attr14, attr15, attr16, attr17, attr18, attr19, attr20, attr21, attr22, attr23, attr24, attr25, attr26, attr27, attr28, attr29, attr30, attr31, attr32, attr33, attr34, attr35, attr36, attr37, attr38, attr39, attr40, attr41, attr42, attr43, attr44, attr45, attr46, attr47, attr48, attr49, attr50, attr51, attr52, attr53, attr54, attr55, attr56, attr57, attr58, attr59, attr60, attr61, attr62, attr63, attr64, attr65, attr66, attr67, attr68, attr69, attr70, attr71, attr72, attr73, attr74, attr75, attr76, attr77, attr78, attr79, attr80, attr81, attr82, attr83, attr84, attr85, attr86, attr87, attr88, attr89, attr90, attr91, attr92, attr93, attr94, attr95, attr96, attr97, attr98, attr99) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

/* insert com.nextlabs.destiny.console.model.EntityAuditLog */ insert into ENTITY_AUDIT_LOG (ACTION, ACTOR, ACTOR_ID, ENTITY_ID, ENTITY_TYPE, NEW_VALUE, OLD_VALUE, TIMESTAMP) values (?, ?, ?, ?, ?, ?, ?, ?);

insert into DEPLOYMENT_REQUEST (executed, time, scheduleTime) values (?, ?, ?);

update DEPLOYMENT_REQUEST set executed=?, time=?, scheduleTime=? where id=?;

select this.id as id0_, this.executed as executed0_, this.time as time0_, this.scheduleTime as schedule4_0_ from DEPLOYMENT_REQUEST this where this.id=?;

select deployment0_.id as id0_, deployment0_.executed as executed0_, deployment0_.time as time0_, deployment0_.scheduleTime as schedule4_0_ from DEPLOYMENT_REQUEST deployment0_ where deployment0_.id=?;

select leafelemen0__1_.ORIGINAL_ID as x0_0_ from DICT_LEAF_ELEMENTS leafelemen0_ inner join DICT_ELEMENTS leafelemen0__1_ on leafelemen0_.ELEMENT_ID=leafelemen0__1_.ID where (((leafelemen0_.TYPE_ID=? )OR(leafelemen0_.TYPE_ID=? ))AND(((leafelemen0_.TYPE_ID=? )AND(((leafelemen0_.String09 LIKE ? ESCAPE '\' )OR(leafelemen0_.String09 LIKE ? ESCAPE '\' )OR(leafelemen0_.String09 LIKE ? ESCAPE '\' )OR(leafelemen0_.String09 LIKE ? ESCAPE '\' ))AND(lower(leafelemen0_.String09)=? )AND(leafelemen0_.String09 is not null ))and(String09 is not null ))AND((leafelemen0_.TYPE_ID=? )AND(((leafelemen0_.String07 LIKE ? ESCAPE '\' )OR(leafelemen0_.String07 LIKE ? ESCAPE '\' )OR(leafelemen0_.String07 LIKE ? ESCAPE '\' )OR(leafelemen0_.String07 LIKE ? ESCAPE '\' ))AND(lower(leafelemen0_.String07)=? )AND(leafelemen0_.String07 is not null ))and(String07 is not null ))AND((leafelemen0_.TYPE_ID=? )AND(((leafelemen0_.String08 LIKE ? ESCAPE '\' )OR(leafelemen0_.String08 LIKE ? ESCAPE '\' )OR(leafelemen0_.String08 LIKE ? ESCAPE '\' )OR(leafelemen0_.String08 LIKE ? ESCAPE '\' ))AND(lower(leafelemen0_.String08)=? )AND(leafelemen0_.String08 is not null ))and(String08 is not null ))))and(leafelemen0__1_.ACTIVE_TO>? )and(leafelemen0__1_.ACTIVE_FROM<=? ) order by leafelemen0__1_.ORIGINAL_ID asc;

insert into tracking_activity_log (id, time, month_nb, day_nb, host_id, user_id, application_id, application_name, action, fromresourcename, fromresourcesize, fromresourceownerid, fromresourcecreateddate, fromresourcemodifieddate, toresourcename, host_name, host_ip, user_name, log_level) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);


select count(*) from RPA_LOG where time < ?;
select min(time) from REPORT_POLICY_ACTIVITY_LOG	;
SELECT from_resource_name AS Dimension, count(*) AS ResultCount FROM RPA_LOG RPA WHERE time >= ? AND time <= ? AND log_level >= ? AND policy_decision LIKE ? GROUP BY from_resource_name ORDER BY ResultCount desc 	;
SELECT policy_fullname AS Dimension, count(*) AS ResultCount FROM RPA_LOG RPA WHERE time >= ? AND time <= ? AND log_level >= ? AND policy_decision LIKE ? GROUP BY policy_fullname ORDER BY ResultCount desc 	;
SELECT user_name AS Dimension, count(*) AS ResultCount FROM RPA_LOG RPA WHERE time >= ? AND time <= ? AND log_level >= ? AND policy_decision LIKE ? GROUP BY user_name ORDER BY ResultCount desc 	;
SELECT c.first_name,c.last_name,c.display_name FROM CACHED_USER c WHERE c.original_id ! = ? AND c.active_from <= ? AND c.active_to > ?	;
SELECT attr39, attr38, attr37, attr36, attr35, attr34, attr33, attr32, attr31, attr30, TO_RESOURCE_NAME, LOG_LEVEL, APPLICATION_NAME, FROM_RESOURCE_PATH, attr49, attr48, attr47, attr46, attr45, attr44, attr43, attr42, attr41, attr40, FROM_RESOURCE_NAME, attr19, attr18, attr17, attr16, attr15, attr14, attr13, attr57, attr12, attr56, attr11, attr55, attr10, attr54, POLICY_NAME, attr53, attr52, attr51, attr50, HOST_NAME, HOST_IP, attr9, POLICY_FULLNAME, attr29, attr6, attr28, attr5, attr27, TIME, attr8, attr26, USER_NAME, attr7, attr25, attr2, attr24, attr1, attr23, attr4, attr22, attr3, attr21, attr20, ACTION, POLICY_DECISION FROM RPA_LOG WHERE id = ?	;
SELECT ID, TIME, MONTH_NB, DAY_NB, HOST_ID, HOST_IP, HOST_NAME, USER_ID, USER_NAME, APPLICATION_ID, APPLICATION_NAME, ACTION, POLICY_ID, POLICY_FULLNAME, POLICY_NAME, POLICY_DECISION, LOG_LEVEL, FROM_RESOURCE_NAME, FROM_RESOURCE_PREFIX, FROM_RESOURCE_PATH, FROM_RESOURCE_SHORT_NAME, TO_RESOURCE_NAME FROM RPA_LOG WHERE id= ? ;





SELECT c.first_name,c.last_name,c.display_name FROM CACHED_USER c WHERE c.original_id ! = ? AND c.active_from <= ? AND c.active_to > ?;

select elementtyp1_.ID as ID, elementtyp1_.VERSION as VERSION, elementtyp1_.name as name, leafelemen0_.String01 as x0_0_, leafelemen0__1_.ORIGINAL_ID as x1_0_, elementtyp1_.ID as x2_0_, leafelemen0__1_.UNIQUE_NAME as x3_0_ from DICT_LEAF_ELEMENTS leafelemen0_ inner join DICT_ELEMENTS leafelemen0__1_ on leafelemen0_.ELEMENT_ID=leafelemen0__1_.ID, DICT_ELEMENT_TYPES elementtyp1_ where leafelemen0_.TYPE_ID=elementtyp1_.ID and (((leafelemen0_.TYPE_ID=? )AND(((leafelemen0_.String01 LIKE ? ESCAPE '\' )OR(leafelemen0_.String01 LIKE ? ESCAPE '\' )OR(leafelemen0_.String01 LIKE ? ESCAPE '\' )OR(leafelemen0_.String01 LIKE ? ESCAPE '\' ))AND(lower(leafelemen0_.String01)=? )AND(leafelemen0_.String01 is not null ))and(String01 is not null ))and(leafelemen0__1_.ACTIVE_TO>? )and(leafelemen0__1_.ACTIVE_FROM<=? ));

select  this.id as id1_, this.default_profile as default_2_1_, this.created_date as created_3_1_, this.modified_date as modified4_1_, this.name as name1_, this.DABS_location as DABS_loc6_1_, this.agent_type as agent_type1_, this.heart_beat_freq_time as heart_be8_1_, this.heart_beat_freq_time_unit as heart_be9_1_, this.log_limit as log_limit1_, this.log_freq_time as log_fre11_1_, this.log_freq_time_unit as log_fre12_1_, this.default_port as default13_1_, this.push_enabled as push_en14_1_, this.password_hash as passwor15_1_, this.curr_act_journ_settings_name as curr_ac16_1_, this.cust_act_journ_settings_id as cust_ac17_1_, activityjo1_.id as id0_, activityjo1_.name as name0_, activityjo1_.customizable as customiz3_0_ from COMM_PROFILE this left outer join ACTIVITY_JOURNALING_SETTINGS activityjo1_ on this.cust_act_journ_settings_id=activityjo1_.id where (this.id=?) order by this.id asc;

insert into HEART_BEAT_RECORD (timestamp) values (?);

select elementtyp1_.ID as ID, elementtyp1_.VERSION as VERSION, elementtyp1_.name as name, leafelemen0_.String01 as x0_0_, leafelemen0__1_.ORIGINAL_ID as x1_0_, elementtyp1_.ID as x2_0_, leafelemen0__1_.UNIQUE_NAME as x3_0_ from DICT_LEAF_ELEMENTS leafelemen0_ inner join DICT_ELEMENTS leafelemen0__1_ on leafelemen0_.ELEMENT_ID=leafelemen0__1_.ID, DICT_ELEMENT_TYPES elementtyp1_ where leafelemen0_.TYPE_ID=elementtyp1_.ID and (((leafelemen0_.TYPE_ID=? )AND(((leafelemen0_.String01 LIKE ?  )OR(leafelemen0_.String01 LIKE ?  )OR(leafelemen0_.String01 LIKE ?  )OR(leafelemen0_.String01 LIKE ?  ))AND(lower(leafelemen0_.String01)=? )AND(leafelemen0_.String01 is not null ))and(String01 is not null ))and(leafelemen0__1_.ACTIVE_TO>? )and(leafelemen0__1_.ACTIVE_FROM<=? ));

select this.id as id1_, this.default_profile as default_2_1_, this.created_date as created_3_1_, this.modified_date as modified4_1_, this.name as name1_, this.DABS_location as DABS_loc6_1_, this.agent_type as agent_type1_, this.heart_beat_freq_time as heart_be8_1_, this.heart_beat_freq_time_unit as heart_be9_1_, this.log_limit as log_limit1_, this.log_freq_time as log_fre11_1_, this.log_freq_time_unit as log_fre12_1_, this.default_port as default13_1_, this.push_enabled as push_en14_1_, this.password_hash as passwor15_1_, this.curr_act_journ_settings_name as curr_ac16_1_, this.cust_act_journ_settings_id as cust_ac17_1_, activityjo1_.id as id0_, activityjo1_.name as name0_, activityjo1_.customizable as customiz3_0_ from COMM_PROFILE this left outer join ACTIVITY_JOURNALING_SETTINGS activityjo1_ on this.cust_act_journ_settings_id=activityjo1_.id where (this.id=?) order by this.id asc;

select elementtyp1_.ID as ID, elementtyp1_.VERSION as VERSION, elementtyp1_.name as name, leafelemen0_.String01 as x0_0_, leafelemen0__1_.ORIGINAL_ID as x1_0_, elementtyp1_.ID as x2_0_, leafelemen0__1_.UNIQUE_NAME as x3_0_ from DICT_LEAF_ELEMENTS leafelemen0_ inner join DICT_ELEMENTS leafelemen0__1_ on leafelemen0_.ELEMENT_ID=leafelemen0__1_.ID, DICT_ELEMENT_TYPES elementtyp1_ where leafelemen0_.TYPE_ID=elementtyp1_.ID and (((leafelemen0_.TYPE_ID=? )AND(((leafelemen0_.String01 LIKE ? )OR(leafelemen0_.String01 LIKE ? )OR(leafelemen0_.String01 LIKE ? )OR(leafelemen0_.String01 LIKE ? ))AND(lower(leafelemen0_.String01)=? )AND(leafelemen0_.String01 is not null ))and(String01 is not null ))and(leafelemen0__1_.ACTIVE_TO>? )and(leafelemen0__1_.ACTIVE_FROM<=? ));

select id,TIME_,host_id,host_ip,host_name,user_id,user_name,application_id,application_name,action,policy_id,policy_decision,decision_request_id,log_level,fromresourcename,fromresourcesize,fromresourceownerid,fromresourcecreateddate,fromresourcemodifieddate,toresourcename from POLICY_ACTIVITY_LOG where sync_done is null ORDER BY user_id ASC, TIME_ ASC;

/* dynamic native SQL query */ SELECT r.user_id user_id, r.user_name, count(r.user_id) total_count from RPA_LOG r WHERE r.policy_decision = ? AND r.day_nb >= ? AND r.day_nb <= ? GROUP BY r.user_id, r.user_name ORDER BY total_count desc;

/* dynamic native SQL query */ SELECT a1.from_resource_name, a1.allow_count, d1.deny_count, (a1.allow_count + d1.deny_count) total_count FROM ( (SELECT rp1.from_resource_name from_resource_name, ra1.allow_decision decision, ISNULL(ra1.allow_count, 0) allow_count FROM ( (SELECT ra.from_resource_name from_resource_name, ra.policy_decision allow_decision, count(ra.from_resource_name) allow_count from RPA_LOG ra WHERE policy_decision = 'A' AND day_nb >= ? AND day_nb <= ? GROUP BY ra.from_resource_name, ra.policy_decision) ra1 RIGHT JOIN (SELECT rp.from_resource_name from_resource_name, 'A' deny_decision from RPA_LOG rp WHERE day_nb >= ? AND day_nb <= ? GROUP BY rp.from_resource_name) rp1 ON (rp1.from_resource_name = ra1.from_resource_name))) a1 INNER JOIN (SELECT rp1.from_resource_name from_resource_name, rp1.deny_decision decision, ISNULL(rd1.deny_count, 0) deny_count FROM ( (SELECT rd.from_resource_name from_resource_name, rd.policy_decision deny_decision, count(rd.from_resource_name) deny_count from RPA_LOG rd WHERE policy_decision = 'D' AND day_nb >= ? AND day_nb <= ? GROUP BY rd.from_resource_name, rd.policy_decision) rd1 RIGHT JOIN (SELECT rp.from_resource_name from_resource_name, 'D' deny_decision from RPA_LOG rp WHERE day_nb >= ? AND day_nb <= ? GROUP BY rp.from_resource_name) rp1 ON (rp1.from_resource_name = rd1.from_resource_name))) d1 ON (a1.from_resource_name = d1.from_resource_name)) ORDER BY total_count DESC;

/* dynamic native SQL query */ SELECT policy_fullname, policy_name, policy_decision, COUNT(policy_fullname) total_count FROM RPA_LOG r WHERE day_nb >= ? AND day_nb <= ? GROUP BY policy_fullname, policy_name, policy_decision ORDER BY total_count DESC;

/* dynamic native SQL query */ SELECT l.fullname, l.deployer FROM (SELECT d.name fullname, d.submitter deployer, k.policy_fullname policy_fullname FROM DEVELOPMENT_ENTITIES d LEFT JOIN (SELECT r.policy_fullname policy_fullname FROM RPA_LOG r WHERE r.day_nb >= ? AND r.day_nb <= ? GROUP BY r.policy_fullname) k ON (k.policy_fullname = CONCAT('/', d.name)) WHERE d.type = 'PO' AND d.status = 'AP' AND d.hidden = 'N') l WHERE l.policy_fullname is null;

/* named HQL query auditLog.lastXRecords */ select auditlog0_.id as id1_4_, auditlog0_.created_date as created_2_4_, auditlog0_.last_updated_by as last_upd3_4_, auditlog0_.last_updated as last_upd4_4_, auditlog0_.created_by as created_5_4_, auditlog0_.version as version6_4_, auditlog0_.component as componen7_4_, auditlog0_.hidden as hidden8_4_, auditlog0_.msgCode as msgCode9_4_, auditlog0_.msgParams as msgPara10_4_ from AUDIT_LOGS auditlog0_ order by auditlog0_.created_date DESC;

insert into policy_activity_log (id, TIME_, month_nb, day_nb, host_id, user_id, application_id, application_name, action, fromresourcename, fromresourcesize, fromresourceownerid, fromresourcecreateddate, fromresourcemodifieddate, toresourcename, policy_id, policy_decision, decision_request_id, host_name, host_ip, user_name, log_level) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ;

/* FROM com.nextlabs.destiny.console.model.SavedSearch */ select savedsearc0_.id as id1_21_, savedsearc0_.created_date as created_2_21_, savedsearc0_.last_updated_by as last_upd3_21_, savedsearc0_.last_updated as last_upd4_21_, savedsearc0_.created_by as created_5_21_, savedsearc0_.version as version6_21_, savedsearc0_.criteria_json as criteria7_21_, savedsearc0_.description as descript8_21_, savedsearc0_.lowercase_name as lowercas9_21_, savedsearc0_.name as name10_21_, savedsearc0_.shared_mode as shared_11_21_, savedsearc0_.status as status12_21_, savedsearc0_.type as type13_21_ from SAVED_SEARCH savedsearc0_;
/* FROM com.nextlabs.destiny.console.model.SuperApplicationUser */ select superappli0_.id as id1_22_, superappli0_.created_date as created_2_22_, superappli0_.displayName as displayN3_22_, superappli0_.email as email4_22_, superappli0_.failed_login_attempts as failed_l5_22_, superappli0_.first_name as first_na6_22_, superappli0_.hide_splash as hide_spl7_22_, superappli0_.initlogin_done as initlogi8_22_, superappli0_.last_name as last_nam9_22_, superappli0_.last_updated_by as last_up10_22_, superappli0_.last_updated as last_up11_22_, superappli0_.locked as locked12_22_, superappli0_.last_logged_time as last_lo13_22_, superappli0_.created_by as created14_22_, superappli0_.password as passwor15_22_, superappli0_.username as usernam16_22_ from SUPER_APPLICATION_USER superappli0_;
/* FROM com.nextlabs.destiny.console.model.TagLabel */ select taglabel0_.id as id1_23_, taglabel0_.created_date as created_2_23_, taglabel0_.last_updated_by as last_upd3_23_, taglabel0_.last_updated as last_upd4_23_, taglabel0_.created_by as created_5_23_, taglabel0_.version as version6_23_, taglabel0_.hidden as hidden7_23_, taglabel0_.tag_key as tag_key8_23_, taglabel0_.label as label9_23_, taglabel0_.status as status10_23_, taglabel0_.type as type11_23_ from TAG_LABELS taglabel0_;
/* FROM com.nextlabs.destiny.console.model.authorization.AccessControl */ select accesscont0_.id as id1_0_, accesscont0_.expression as expressi2_0_, accesscont0_.request_method as request_3_0_, accesscont0_.url_pattern as url_patt4_0_ from ACCESS_CONTROL accesscont0_;
/* dynamic native SQL query */ SELECT ID, USERNAME, FIRST_NAME, LAST_NAME, DOMAIN_ID, PRIMARY_GROUP_ID, LAST_LOGGED_TIME, HIDE_SPLASH, LAST_UPDATED, USER_TYPE, AUTH_HANDLER_ID    FROM APPLICATION_USER a WHERE a.status = ?;
/* named HQL query appUserProperties.findByUserId */ select appuserpro0_.id as id1_3_, appuserpro0_.created_date as created_2_3_, appuserpro0_.last_updated_by as last_upd3_3_, appuserpro0_.last_updated as last_upd4_3_, appuserpro0_.created_by as created_5_3_, appuserpro0_.version as version6_3_, appuserpro0_.data_type as data_typ7_3_, appuserpro0_.prop_key as prop_key8_3_, appuserpro0_.super_user_id as super_us9_3_, appuserpro0_.user_id as user_id10_3_, appuserpro0_.prop_value as prop_va11_3_ from APP_USER_PROPERTIES appuserpro0_ where appuserpro0_.user_id=? order by appuserpro0_.prop_key;
/* named HQL query policy.findActiveByType */ select policydeve0_.id as id1_9_, policydeve0_.appql as appql2_9_, policydeve0_.created as created3_9_, policydeve0_.description as descript4_9_, policydeve0_.extended_desc as extended5_9_, policydeve0_.has_dependencies as has_depe6_9_, policydeve0_.hidden as hidden7_9_, policydeve0_.is_sub_policy as is_sub_p8_9_, policydeve0_.last_modified as last_mod9_9_, policydeve0_.last_updated as last_up10_9_, policydeve0_.modifier as modifie11_9_, policydeve0_.owner as owner12_9_, policydeve0_.pql as pql13_9_, policydeve0_.status as status14_9_, policydeve0_.submitted_time as submitt15_9_, policydeve0_.submitter as submitt16_9_, policydeve0_.name as name17_9_, policydeve0_.type as type18_9_, policydeve0_.version as version19_9_ from DEVELOPMENT_ENTITIES policydeve0_ where policydeve0_.hidden=? and policydeve0_.status<>? and policydeve0_.type=?;
/* named HQL query tag.findByKey */ select taglabel0_.id as id1_23_, taglabel0_.created_date as created_2_23_, taglabel0_.last_updated_by as last_upd3_23_, taglabel0_.last_updated as last_upd4_23_, taglabel0_.created_by as created_5_23_, taglabel0_.version as version6_23_, taglabel0_.hidden as hidden7_23_, taglabel0_.tag_key as tag_key8_23_, taglabel0_.label as label9_23_, taglabel0_.status as status10_23_, taglabel0_.type as type11_23_ from TAG_LABELS taglabel0_ where lower(taglabel0_.tag_key)=? and taglabel0_.type=? order by taglabel0_.label;
/* select count(generatedAlias0) from OperatorConfig as generatedAlias0 where 1=1 */ select count(operatorco0_.id) as col_0_0_ from OPERATOR_CONFIG operatorco0_ where 1=1;
/* select generatedAlias0 from DelegateModel as generatedAlias0 where ( generatedAlias0.shortName=:param0 ) and ( generatedAlias0.status<>:param1 ) */ select delegatemo0_.id as id2_19_, delegatemo0_.created_date as created_3_19_, delegatemo0_.last_updated_by as last_upd4_19_, delegatemo0_.last_updated as last_upd5_19_, delegatemo0_.created_by as created_6_19_, delegatemo0_.version as version7_19_, delegatemo0_.description as descript8_19_, delegatemo0_.name as name9_19_, delegatemo0_.short_name as short_n10_19_, delegatemo0_.status as status11_19_, delegatemo0_.type as type12_19_ from POLICY_MODEL delegatemo0_ where delegatemo0_.discriminator='DELEGATION' and delegatemo0_.short_name=? and delegatemo0_.status<>?;
/* select generatedAlias0 from DelegateModel as generatedAlias0 where ( generatedAlias0.type=:param0 ) or ( generatedAlias0.type=:param1 ) */ select delegatemo0_.id as id2_19_, delegatemo0_.created_date as created_3_19_, delegatemo0_.last_updated_by as last_upd4_19_, delegatemo0_.last_updated as last_upd5_19_, delegatemo0_.created_by as created_6_19_, delegatemo0_.version as version7_19_, delegatemo0_.description as descript8_19_, delegatemo0_.name as name9_19_, delegatemo0_.short_name as short_n10_19_, delegatemo0_.status as status11_19_, delegatemo0_.type as type12_19_ from POLICY_MODEL delegatemo0_ where delegatemo0_.discriminator='DELEGATION' and (delegatemo0_.type=? or delegatemo0_.type=?);
/* select generatedAlias0 from PolicyDevelopmentEntity as generatedAlias0 where ( generatedAlias0.title=:param0 ) and ( generatedAlias0.status<>:param1 ) */ select policydeve0_.id as id1_9_, policydeve0_.appql as appql2_9_, policydeve0_.created as created3_9_, policydeve0_.description as descript4_9_, policydeve0_.extended_desc as extended5_9_, policydeve0_.has_dependencies as has_depe6_9_, policydeve0_.hidden as hidden7_9_, policydeve0_.is_sub_policy as is_sub_p8_9_, policydeve0_.last_modified as last_mod9_9_, policydeve0_.last_updated as last_up10_9_, policydeve0_.modifier as modifie11_9_, policydeve0_.owner as owner12_9_, policydeve0_.pql as pql13_9_, policydeve0_.status as status14_9_, policydeve0_.submitted_time as submitt15_9_, policydeve0_.submitter as submitt16_9_, policydeve0_.name as name17_9_, policydeve0_.type as type18_9_, policydeve0_.version as version19_9_ from DEVELOPMENT_ENTITIES policydeve0_ where policydeve0_.name=? and policydeve0_.status<>?;
/* select generatedAlias0 from PolicyModel as generatedAlias0 where ( generatedAlias0.type=:param0 ) or ( generatedAlias0.type=:param1 ) */ select policymode0_.id as id2_19_, policymode0_.created_date as created_3_19_, policymode0_.last_updated_by as last_upd4_19_, policymode0_.last_updated as last_upd5_19_, policymode0_.created_by as created_6_19_, policymode0_.version as version7_19_, policymode0_.description as descript8_19_, policymode0_.name as name9_19_, policymode0_.short_name as short_n10_19_, policymode0_.status as status11_19_, policymode0_.type as type12_19_, policymode0_.discriminator as discrimi1_19_ from POLICY_MODEL policymode0_ where policymode0_.type=? or policymode0_.type=?;
SELECT * FROM "connection_test_table_sa3662";
SELECT ID, TYPE, CONFIG_DATA_JSON FROM AUTH_HANDLER_REGISTRY;
select actions0_.plcy_model_id as plcy_mo11_19_0_, actions0_.id as id1_14_0_, actions0_.id as id1_14_1_, actions0_.created_date as created_2_14_1_, actions0_.last_updated_by as last_upd3_14_1_, actions0_.last_updated as last_upd4_14_1_, actions0_.created_by as created_5_14_1_, actions0_.version as version6_14_1_, actions0_.name as name7_14_1_, actions0_.short_code as short_co8_14_1_, actions0_.short_name as short_na9_14_1_, actions0_.sort_order as sort_or10_14_1_ from PM_ACTION_CONFIG actions0_ where actions0_.plcy_model_id=?;
select attributes0_.plcy_model_id as plcy_mo13_19_0_, attributes0_.id as id1_15_0_, attributes0_.id as id1_15_1_, attributes0_.created_date as created_2_15_1_, attributes0_.last_updated_by as last_upd3_15_1_, attributes0_.last_updated as last_upd4_15_1_, attributes0_.created_by as created_5_15_1_, attributes0_.version as version6_15_1_, attributes0_.data_type as data_typ7_15_1_, attributes0_.name as name8_15_1_, attributes0_.policy_model_id as policy_12_15_1_, attributes0_.reg_ex_pattern as reg_ex_p9_15_1_, attributes0_.short_name as short_n10_15_1_, attributes0_.sort_order as sort_or11_15_1_, policymode1_.id as id2_19_2_, policymode1_.created_date as created_3_19_2_, policymode1_.last_updated_by as last_upd4_19_2_, policymode1_.last_updated as last_upd5_19_2_, policymode1_.created_by as created_6_19_2_, policymode1_.version as version7_19_2_, policymode1_.description as descript8_19_2_, policymode1_.name as name9_19_2_, policymode1_.short_name as short_n10_19_2_, policymode1_.status as status11_19_2_, policymode1_.type as type12_19_2_, policymode1_.discriminator as discrimi1_19_2_ from PM_ATTRIBUTE_CONFIG attributes0_ left outer join POLICY_MODEL policymode1_ on attributes0_.policy_model_id=policymode1_.id where attributes0_.plcy_model_id=?;
select componentd0_.id as id, componentd0_.name as name, componentd0_.type as type, componentd0_.typeDisplayName as typeDisp4_, componentd0_.callbackURL as callback5_, componentd0_.componentURL as componen6_, componentd0_.lastHeartbeat as lastHear7_, componentd0_.heartbeatRate as heartbea8_, componentd0_.version as version from COMPONENT componentd0_ where (componentd0_.name=? );
select componentd0_.id as id, componentd0_.name as name, componentd0_.type as type, componentd0_.typeDisplayName as typeDisp4_, componentd0_.callbackURL as callback5_, componentd0_.componentURL as componen6_, componentd0_.lastHeartbeat as lastHear7_, componentd0_.heartbeatRate as heartbea8_, componentd0_.version as version from COMPONENT componentd0_ where (componentd0_.type=? )and(componentd0_.callbackURL=? );
select customappd0_.id as id, customappd0_.name as name, customappd0_.version as version, customappd0_.description as descript4_ from CUSTOM_APP customappd0_;
select customrepo0_.id as id, customrepo0_.app_ref_id as app_ref_id, customrepo0_.file_content as file_con3_ from REPORT_CUSTOM_APP_UI customrepo0_;
select customrepo0_.id as id, customrepo0_.app_ref_id as app_ref_id, customrepo0_.title as title, customrepo0_.description as descript4_ from REPORT_CUSTOM_APP customrepo0_;
select customrepo0_.id as id, customrepo0_.position as position, customrepo0_.custom_report_id as custom_r3_, customrepo0_.name as name, customrepo0_.content as content from REPORT_CUSTOM_APP_FILES customrepo0_;
select deployment0_.id as id, deployment0_.version as version, deployment0_.development_id as developm3_, deployment0_.dep_record_id as dep_reco4_, deployment0_.name as name, deployment0_.description as descript6_, deployment0_.pql as pql, deployment0_.processedpql as processe8_, deployment0_.override_cnt as override9_, deployment0_.active_from as active_10_, deployment0_.active_to as active_to, deployment0_.hidden as hidden, deployment0_.original_version as origina13_, deployment0_.last_modified as last_mo14_, deployment0_.modifier as modifier, deployment0_.submitted_time as submitt16_, deployment0_.submitter as submitter from deployment_entities deployment0_, deployment_records deployment1_, development_entities developmen2_ where deployment0_.development_id=developmen2_.id and ((deployment0_.override_cnt=0 )and(deployment0_.pql is not null )and(deployment0_.active_to>? )and(deployment0_.active_from<=? )and(deployment0_.active_from>? )and(deployment1_.deployment_type=?  and deployment0_.dep_record_id=deployment1_.id)and(developmen2_.type in(?) and deployment0_.development_id=developmen2_.id)) order by  developmen2_.id asc;
select deployment0_.id as id0_, deployment0_.action_type as action_t2_0_, deployment0_.deployment_type as deployme3_0_, deployment0_.as_of as as_of0_, deployment0_.when_requested as when_req5_0_, deployment0_.when_cancelled as when_can6_0_, deployment0_.hidden as hidden0_, deployment0_.deployer as deployer0_ from deployment_records deployment0_ where deployment0_.id=?;
select developmen0_.id as id0_, developmen0_.version as version0_, developmen0_.owner as owner0_, developmen0_.appql as appql0_, developmen0_.name as name0_, developmen0_.description as descript6_0_, developmen0_.pql as pql0_, developmen0_.status as status0_, developmen0_.type as type0_, developmen0_.last_updated as last_up10_0_, developmen0_.created as created0_, developmen0_.last_modified as last_mo12_0_, developmen0_.modifier as modifier0_, developmen0_.submitted_time as submitt14_0_, developmen0_.submitter as submitter0_, developmen0_.hidden as hidden0_, developmen0_.has_dependencies as has_dep17_0_, developmen0_.is_sub_policy as is_sub_18_0_ from development_entities developmen0_ where developmen0_.id=?;
select eventdo0_.id as id, eventdo0_.name as name from EVENT eventdo0_ where (eventdo0_.name=? );
select fields0_.PARENT_TYPE_ID as PARENT_T9___, fields0_.ID as ID__, fields0_.ID as ID0_, fields0_.VERSION as VERSION0_, fields0_.name as name0_, fields0_.name_upper as name_upper0_, fields0_.type as type0_, fields0_.label as label0_, fields0_.deleted as deleted0_, fields0_.mapping as mapping0_, fields0_.PARENT_TYPE_ID as PARENT_T9_0_ from DICT_TYPE_FIELDS fields0_ where fields0_.PARENT_TYPE_ID=?;
--select heartbeatr0_.id as id, heartbeatr0_.timestamp as timestamp from HEART_BEAT_RECORD heartbeatr0_ where (timestamp<? );
select loggedacti0_.settings_id as settings1___, loggedacti0_.action as action__ from ACT_JOURN_SETTINGS_LOGGED_ACTS loggedacti0_ where loggedacti0_.settings_id=?;
select min(updatereco0_.end_time) as x0_0_ from DICT_UPDATES updatereco0_ where ((not exists(select updatereco1_.ID from DICT_UPDATES updatereco1_ where (updatereco1_.ACTIVE_FROM<=updatereco0_.ACTIVE_FROM )and(updatereco1_.ACTIVE_TO>updatereco0_.ACTIVE_FROM )and(updatereco1_.is_successful='N' ))))and(updatereco0_.is_successful='Y' )and(updatereco0_.ACTIVE_FROM>? );
select obligation0_.plcy_model_id as plcy_mo11_19_0_, obligation0_.id as id1_17_0_, obligation0_.id as id1_17_1_, obligation0_.created_date as created_2_17_1_, obligation0_.last_updated_by as last_upd3_17_1_, obligation0_.last_updated as last_upd4_17_1_, obligation0_.created_by as created_5_17_1_, obligation0_.version as version6_17_1_, obligation0_.name as name7_17_1_, obligation0_.run_at as run_at8_17_1_, obligation0_.short_name as short_na9_17_1_, obligation0_.sort_order as sort_or10_17_1_ from PM_OBLIGATION_CONFIG obligation0_ where obligation0_.plcy_model_id=?;
select operatorco0_.attribute_id as attribut1_15_0_, operatorco0_.operator_id as operator2_16_0_, operatorco1_.id as id1_12_1_, operatorco1_.created_date as created_2_12_1_, operatorco1_.last_updated_by as last_upd3_12_1_, operatorco1_.last_updated as last_upd4_12_1_, operatorco1_.created_by as created_5_12_1_, operatorco1_.version as version6_12_1_, operatorco1_.data_type as data_typ7_12_1_, operatorco1_.operator_key as operator8_12_1_, operatorco1_.label as label9_12_1_ from PM_ATTRIB_CONFIG_OPER_CONFIG operatorco0_ inner join OPERATOR_CONFIG operatorco1_ on operatorco0_.operator_id=operatorco1_.id where operatorco0_.attribute_id=?;
select parameters0_.obligation_id as obligat16_17_0_, parameters0_.id as id1_18_0_, parameters0_.id as id1_18_1_, parameters0_.created_date as created_2_18_1_, parameters0_.last_updated_by as last_upd3_18_1_, parameters0_.last_updated as last_upd4_18_1_, parameters0_.created_by as created_5_18_1_, parameters0_.version as version6_18_1_, parameters0_.default_value as default_7_18_1_, parameters0_.is_editable as is_edita8_18_1_, parameters0_.is_hidden as is_hidde9_18_1_, parameters0_.list_values as list_va10_18_1_, parameters0_.is_mandatory as is_mand11_18_1_, parameters0_.name as name12_18_1_, parameters0_.short_name as short_n13_18_1_, parameters0_.sort_order as sort_or14_18_1_, parameters0_.data_type as data_ty15_18_1_ from PM_PARAMETER_CONFIG parameters0_ where parameters0_.obligation_id=?;
select registrati0_.EVENT_ID as EVENT_ID__, registrati0_.id as id__, registrati0_.COMPONENT_ID as COMPONEN4___, registrati0_.id as id1_, registrati0_.lastModified as lastModi2_1_, registrati0_.isActive as isActive1_, registrati0_.COMPONENT_ID as COMPONEN4_1_, registrati0_.EVENT_ID as EVENT_ID1_, componentd1_.id as id0_, componentd1_.name as name0_, componentd1_.type as type0_, componentd1_.typeDisplayName as typeDisp4_0_, componentd1_.callbackURL as callback5_0_, componentd1_.componentURL as componen6_0_, componentd1_.lastHeartbeat as lastHear7_0_, componentd1_.heartbeatRate as heartbea8_0_, componentd1_.version as version0_ from EVENT_REGISTRATION registrati0_ left outer join COMPONENT componentd1_ on registrati0_.COMPONENT_ID=componentd1_.id where registrati0_.EVENT_ID=?;
select seeditems0_.SEED_COMM_PROFILE_ID as SEED_COM1___, seeditems0_.COMM_PROFILE_ID as COMM_PRO2___, seeditems0_.SEED_NAME as SEED_NAME__ from COMM_PROFILE_SEED_ITEMS seeditems0_ where seeditems0_.SEED_COMM_PROFILE_ID=?;
select tags0_.dev_entity_id as dev_enti1_9_0_, tags0_.tag_id as tag_id2_10_0_, taglabel1_.id as id1_23_1_, taglabel1_.created_date as created_2_23_1_, taglabel1_.last_updated_by as last_upd3_23_1_, taglabel1_.last_updated as last_upd4_23_1_, taglabel1_.created_by as created_5_23_1_, taglabel1_.version as version6_23_1_, taglabel1_.hidden as hidden7_23_1_, taglabel1_.tag_key as tag_key8_23_1_, taglabel1_.label as label9_23_1_, taglabel1_.status as status10_23_1_, taglabel1_.type as type11_23_1_ from DEVELOPMENT_ENTITIES_TAGS tags0_ inner join TAG_LABELS taglabel1_ on tags0_.tag_id=taglabel1_.id where tags0_.dev_entity_id=?;
select tags0_.plcy_model_id as plcy_mod1_19_0_, tags0_.tag_id as tag_id2_20_0_, taglabel1_.id as id1_23_1_, taglabel1_.created_date as created_2_23_1_, taglabel1_.last_updated_by as last_upd3_23_1_, taglabel1_.last_updated as last_upd4_23_1_, taglabel1_.created_by as created_5_23_1_, taglabel1_.version as version6_23_1_, taglabel1_.hidden as hidden7_23_1_, taglabel1_.tag_key as tag_key8_23_1_, taglabel1_.label as label9_23_1_, taglabel1_.status as status10_23_1_, taglabel1_.type as type11_23_1_ from POLICY_MODEL_TAGS tags0_ inner join TAG_LABELS taglabel1_ on tags0_.tag_id=taglabel1_.id where tags0_.plcy_model_id=?;
select this.ID as ID0_, this.VERSION as VERSION0_, this.domain_name as domain_n3_0_, this.enrollment_type as enrollme4_0_, this.isRecurring as isRecurr5_0_, this.isActive as isActive0_ from DICT_ENROLLMENTS this where this.isActive=?;
select this.ID as ID0_, this.VERSION as VERSION0_, this.name as name0_ from DICT_ELEMENT_TYPES this where this.name=?;
select this.id as id0_, this.lastUpdated as lastUpda2_0_, this.type as type0_ from RESOURCE_CACHE_STATE this where this.type=?;
select this.id as id0_, this.last_updated as last_upd2_0_ from COMM_PROFILE_SEED this where 1=1;
select this.id as id0_, this.name as name0_, this.customizable as customiz3_0_ from ACTIVITY_JOURNALING_SETTINGS this where this.name=?;
select this.id as id0_, this.name as name0_, this.description as descript3_0_, this.criteria_json as criteria4_0_, this.alert_message as alert_me5_0_, this.email_address as email_ad6_0_, this.auto_dismiss as auto_dis7_0_, this.email_admin as email_ad8_0_, this.is_active as is_active0_, this.created_datetime as created10_0_, this.updated_datetime as updated11_0_, this.is_deleted as is_deleted0_, this.uuid as uuid0_, this.is_archived as is_arch14_0_, this.shared_mode as shared_15_0_, this.owner_id as owner_id0_, this.pql_data as pql_data0_ from MONITOR this where (this.is_active=? and (this.is_deleted=? and this.is_archived=?));
select this.id as id2_, this.lastModified as lastModi2_2_, this.isActive as isActive2_, this.COMPONENT_ID as COMPONEN4_2_, this.EVENT_ID as EVENT_ID2_, componentd1_.id as id0_, componentd1_.name as name0_, componentd1_.type as type0_, componentd1_.typeDisplayName as typeDisp4_0_, componentd1_.callbackURL as callback5_0_, componentd1_.componentURL as componen6_0_, componentd1_.lastHeartbeat as lastHear7_0_, componentd1_.heartbeatRate as heartbea8_0_, componentd1_.version as version0_, eventdo2_.id as id1_, eventdo2_.name as name1_ from EVENT_REGISTRATION this left outer join COMPONENT componentd1_ on this.COMPONENT_ID=componentd1_.id left outer join EVENT eventdo2_ on this.EVENT_ID=eventdo2_.id where this.lastModified>=? and not this.COMPONENT_ID=?;
--select top 1 this.id as id1_, this.default_profile as default_2_1_, this.created_date as created_3_1_, this.modified_date as modified4_1_, this.name as name1_, this.DABS_location as DABS_loc6_1_, this.agent_type as agent_type1_, this.heart_beat_freq_time as heart_be8_1_, this.heart_beat_freq_time_unit as heart_be9_1_, this.log_limit as log_limit1_, this.log_freq_time as log_fre11_1_, this.log_freq_time_unit as log_fre12_1_, this.default_port as default13_1_, this.push_enabled as push_en14_1_, this.password_hash as passwor15_1_, this.curr_act_journ_settings_name as curr_ac16_1_, this.cust_act_journ_settings_id as cust_ac17_1_, activityjo1_.id as id0_, activityjo1_.name as name0_, activityjo1_.customizable as customiz3_0_ from COMM_PROFILE this left outer join ACTIVITY_JOURNALING_SETTINGS activityjo1_ on this.cust_act_journ_settings_id=activityjo1_.id where (this.id=?) order by this.id asc;
--select top 30 this.id as id0_, this.creationTime as creation2_0_, this.dataObjectName as dataObje3_0_, this.resultObjectName as resultOb4_0_, this.availableRowCount as availabl5_0_, this.minValue as minValue0_, this.maxValue as maxValue0_, this.sumValue as sumValue0_, this.totalRowCount as totalRow9_0_ from STORED_QUERY this where this.creationTime<?;
update COMPONENT set name=?, type=?, typeDisplayName=?, callbackURL=?, componentURL=?, lastHeartbeat=?, heartbeatRate=?, version=? where id=?;
update EVENT_REGISTRATION set lastModified=?, isActive=?, COMPONENT_ID=?, EVENT_ID=? where id=?;
update RESOURCE_CACHE_STATE set lastUpdated=?, type=? where id=?;

-- mysql sample sql

SELECT
  salesperson.name,
  -- find maximum sale size for this salesperson
  (SELECT MAX(amount) AS amount
    FROM all_sales
    WHERE all_sales.salesperson_id = salesperson.id)
  AS amount,
  -- find customer for this maximum size
  (SELECT customer_name
    FROM all_sales
    WHERE all_sales.salesperson_id = salesperson.id
    AND all_sales.amount =
         -- find maximum size, again
         (SELECT MAX(amount) AS amount
           FROM all_sales
           WHERE all_sales.salesperson_id = salesperson.id))
  AS customer_name
FROM
  salesperson;


SELECT ROW_NUMBER() OVER(PARTITION BY PostalCode ORDER BY SalesYTD DESC) AS "Row Number",
    p.LastName, s.SalesYTD, a.PostalCode
FROM Sales.SalesPerson AS s
    INNER JOIN Person.Person AS p
        ON s.BusinessEntityID = p.BusinessEntityID
    INNER JOIN Person.Address AS a
        ON a.AddressID = p.BusinessEntityID
WHERE TerritoryID IS NOT NULL
    AND SalesYTD <> 0
ORDER BY PostalCode;

