//
// Created by jeff on 2019/9/3.
//

//redirect some API
#include "ODBCMgrApi.h"

#define LINKER_PARA_EXPORT(funname, ordinal) /export:##funname=odbc32_ms.##funname,@ordinal
#define STR(str) #str
#define TMP_STR(tmp) STR(tmp)

#define REDIRECT_ODBC_API(funname,ordinal)  comment(linker,TMP_STR(LINKER_PARA_EXPORT(funname,ordinal)))


#pragma REDIRECT_ODBC_API(CloseODBCPerfData,79)
#pragma REDIRECT_ODBC_API(CollectODBCPerfData,80)
#pragma REDIRECT_ODBC_API(CursorLibLockDbc,81)
#pragma REDIRECT_ODBC_API(CursorLibLockDesc,82)
#pragma REDIRECT_ODBC_API(CursorLibLockStmt,83)
#pragma REDIRECT_ODBC_API(CursorLibTransact,85)
#pragma REDIRECT_ODBC_API(DllBidEntryPoint,87)
#pragma REDIRECT_ODBC_API(GetODBCSharedData,88)
#pragma REDIRECT_ODBC_API(LockHandle,89)
#pragma REDIRECT_ODBC_API(ODBCGetTryWaitValue,84)
#pragma REDIRECT_ODBC_API(ODBCInternalConnectW,90)
#pragma REDIRECT_ODBC_API(ODBCQualifyFileDSNW,301)
#pragma REDIRECT_ODBC_API(ODBCSetTryWaitValue,86)
#pragma REDIRECT_ODBC_API(OpenODBCPerfData,91)
#pragma REDIRECT_ODBC_API(PostComponentError,92)
#pragma REDIRECT_ODBC_API(PostODBCComponentError,93)
#pragma REDIRECT_ODBC_API(PostODBCError,94)

#pragma REDIRECT_ODBC_API(SearchStatusCode,97)
#pragma REDIRECT_ODBC_API(VFreeErrors,98)
#pragma REDIRECT_ODBC_API(VRetrieveDriverErrorsRowCol,99)
#pragma REDIRECT_ODBC_API(ValidateErrorQueue,100)
#pragma REDIRECT_ODBC_API(g_hHeapMalloc,101)

// #pragma REDIRECT_ODBC_API(SQLAllocConnect,1)
// #pragma REDIRECT_ODBC_API(SQLAllocEnv,2)
//#pragma REDIRECT_ODBC_API(SQLAllocHandle,24)
// #pragma REDIRECT_ODBC_API(SQLAllocHandleStd, 77)
// #pragma REDIRECT_ODBC_API(SQLAllocStmt,3)

// #pragma REDIRECT_ODBC_API(SQLBindCol,4)
// #pragma REDIRECT_ODBC_API(SQLBindParam,25)
// #pragma REDIRECT_ODBC_API(SQLBindParameter,72)
//#pragma REDIRECT_ODBC_API(SQLBrowseConnect,55)
//#pragma REDIRECT_ODBC_API(SQLBrowseConnectA,255)
//#pragma REDIRECT_ODBC_API(SQLBrowseConnectW,155)
// #pragma REDIRECT_ODBC_API(SQLBulkOperations,78)
//#pragma REDIRECT_ODBC_API(SQLCancel,5)//ENTER_STMT_cancel
//#pragma REDIRECT_ODBC_API(SQLCancelHandle,95)
// #pragma REDIRECT_ODBC_API(SQLCloseCursor,26)
// #pragma REDIRECT_ODBC_API(SQLColAttribute,27)
// #pragma REDIRECT_ODBC_API(SQLColAttributeA,227)
// #pragma REDIRECT_ODBC_API(SQLColAttributeW,127)
// #pragma REDIRECT_ODBC_API(SQLColAttributes,6)
// #pragma REDIRECT_ODBC_API(SQLColAttributesA,206)
// #pragma REDIRECT_ODBC_API(SQLColAttributesW,106)
// #pragma REDIRECT_ODBC_API(SQLColumnPrivileges,56)
// #pragma REDIRECT_ODBC_API(SQLColumnPrivilegesA,256)
// #pragma REDIRECT_ODBC_API(SQLColumnPrivilegesW,156)
// #pragma REDIRECT_ODBC_API(SQLColumns,40)
// #pragma REDIRECT_ODBC_API(SQLColumnsA,240)
// #pragma REDIRECT_ODBC_API(SQLColumnsW,140)
//#pragma REDIRECT_ODBC_API(SQLCompleteAsync,96)
//#pragma REDIRECT_ODBC_API(SQLConnect,7)
//#pragma REDIRECT_ODBC_API(SQLConnectA,207)
//#pragma REDIRECT_ODBC_API(SQLConnectW,107)
//#pragma REDIRECT_ODBC_API(SQLCopyDesc,28)//ENTER_DESC
//#pragma REDIRECT_ODBC_API(SQLDataSources,57)//ENTER_HENV
//#pragma REDIRECT_ODBC_API(SQLDataSourcesA,257)//ENTER_HENV
//#pragma REDIRECT_ODBC_API(SQLDataSourcesW,157)//ENTER_HENV
// #pragma REDIRECT_ODBC_API(SQLDescribeCol,8)
// #pragma REDIRECT_ODBC_API(SQLDescribeColA,208)
// #pragma REDIRECT_ODBC_API(SQLDescribeColW,108)
// #pragma REDIRECT_ODBC_API(SQLDescribeParam,58)
//#pragma REDIRECT_ODBC_API(SQLDisconnect,9)
//#pragma REDIRECT_ODBC_API(SQLDriverConnect,41)
//#pragma REDIRECT_ODBC_API(SQLDriverConnectA,241)
//#pragma REDIRECT_ODBC_API(SQLDriverConnectW,141)
//#pragma REDIRECT_ODBC_API(SQLDrivers,71)
//#pragma REDIRECT_ODBC_API(SQLDriversA,271)
//#pragma REDIRECT_ODBC_API(SQLDriversW,171)
// #pragma REDIRECT_ODBC_API(SQLEndTran,29)
// #pragma REDIRECT_ODBC_API(SQLError,10)
// #pragma REDIRECT_ODBC_API(SQLErrorA,210)
// #pragma REDIRECT_ODBC_API(SQLErrorW,110)
//#pragma REDIRECT_ODBC_API(SQLExecDirect,11)
//#pragma REDIRECT_ODBC_API(SQLExecDirectA,211)
//#pragma REDIRECT_ODBC_API(SQLExecDirectW,111)
// #pragma REDIRECT_ODBC_API(SQLExecute,12)
// #pragma REDIRECT_ODBC_API(SQLExtendedFetch,59)
// #pragma REDIRECT_ODBC_API(SQLFetch,13)
// #pragma REDIRECT_ODBC_API(SQLFetchScroll,30)
// #pragma REDIRECT_ODBC_API(SQLForeignKeys,60)
// #pragma REDIRECT_ODBC_API(SQLForeignKeysA,260)
// #pragma REDIRECT_ODBC_API(SQLForeignKeysW,160)
// #pragma REDIRECT_ODBC_API(SQLFreeConnect,14)
//#pragma REDIRECT_ODBC_API(SQLFreeEnv,15)
//#pragma REDIRECT_ODBC_API(SQLFreeHandle,31)
// #pragma REDIRECT_ODBC_API(SQLFreeStmt,16)
// #pragma REDIRECT_ODBC_API(SQLGetConnectAttr,32)
// #pragma REDIRECT_ODBC_API(SQLGetConnectAttrA,232)
// #pragma REDIRECT_ODBC_API(SQLGetConnectAttrW,132)
// #pragma REDIRECT_ODBC_API(SQLGetConnectOption,42)
// #pragma REDIRECT_ODBC_API(SQLGetConnectOptionA,242)
// #pragma REDIRECT_ODBC_API(SQLGetConnectOptionW,142)
// #pragma REDIRECT_ODBC_API(SQLGetCursorName,17)
// #pragma REDIRECT_ODBC_API(SQLGetCursorNameA,217)
// #pragma REDIRECT_ODBC_API(SQLGetCursorNameW,117)
// #pragma REDIRECT_ODBC_API(SQLGetData,43)
//#pragma REDIRECT_ODBC_API(SQLGetDescField,33)//ENTER_DESC
//#pragma REDIRECT_ODBC_API(SQLGetDescFieldA,233)//ENTER_DESC
//#pragma REDIRECT_ODBC_API(SQLGetDescFieldW,133)//ENTER_DESC
//#pragma REDIRECT_ODBC_API(SQLGetDescRec,34)//ENTER_DESC
//#pragma REDIRECT_ODBC_API(SQLGetDescRecA,234)//ENTER_DESC
//#pragma REDIRECT_ODBC_API(SQLGetDescRecW,134)//ENTER_DESC
// #pragma REDIRECT_ODBC_API(SQLGetDiagField,35)
// #pragma REDIRECT_ODBC_API(SQLGetDiagFieldA,235)
// #pragma REDIRECT_ODBC_API(SQLGetDiagFieldW,135)

//#pragma REDIRECT_ODBC_API(SQLGetDiagRec,36)
//#pragma REDIRECT_ODBC_API(SQLGetDiagRecA,236)
//#pragma REDIRECT_ODBC_API(SQLGetDiagRecW,136)

// #pragma REDIRECT_ODBC_API(SQLGetEnvAttr,37)
// #pragma REDIRECT_ODBC_API(SQLGetFunctions,44)
//#pragma REDIRECT_ODBC_API(SQLGetInfo,45)
// #pragma REDIRECT_ODBC_API(SQLGetInfoA,245)
// #pragma REDIRECT_ODBC_API(SQLGetInfoW,145)
// #pragma REDIRECT_ODBC_API(SQLGetStmtAttr,38)
// #pragma REDIRECT_ODBC_API(SQLGetStmtAttrA,238)
// #pragma REDIRECT_ODBC_API(SQLGetStmtAttrW,138)
// #pragma REDIRECT_ODBC_API(SQLGetStmtOption,46)
// #pragma REDIRECT_ODBC_API(SQLGetTypeInfo,47)
// #pragma REDIRECT_ODBC_API(SQLGetTypeInfoA,247)
// #pragma REDIRECT_ODBC_API(SQLGetTypeInfoW,147)
// #pragma REDIRECT_ODBC_API(SQLMoreResults,61)
// #pragma REDIRECT_ODBC_API(SQLNativeSql,62)
// #pragma REDIRECT_ODBC_API(SQLNativeSqlA,262)
// #pragma REDIRECT_ODBC_API(SQLNativeSqlW,162)
// #pragma REDIRECT_ODBC_API(SQLNumParams,63)
// #pragma REDIRECT_ODBC_API(SQLNumResultCols,18)
// #pragma REDIRECT_ODBC_API(SQLParamData,48)
// #pragma REDIRECT_ODBC_API(SQLParamOptions,64)
// #pragma REDIRECT_ODBC_API(SQLPrepare,19)
// #pragma REDIRECT_ODBC_API(SQLPrepareA,219)
// #pragma REDIRECT_ODBC_API(SQLPrepareW,119)
// #pragma REDIRECT_ODBC_API(SQLPrimaryKeys,65)
// #pragma REDIRECT_ODBC_API(SQLPrimaryKeysA,265)
// #pragma REDIRECT_ODBC_API(SQLPrimaryKeysW,165)
// #pragma REDIRECT_ODBC_API(SQLProcedureColumns,66)
// #pragma REDIRECT_ODBC_API(SQLProcedureColumnsA,266)
// #pragma REDIRECT_ODBC_API(SQLProcedureColumnsW,166)
// #pragma REDIRECT_ODBC_API(SQLProcedures,67)
// #pragma REDIRECT_ODBC_API(SQLProceduresA,267)
// #pragma REDIRECT_ODBC_API(SQLProceduresW,167)
// #pragma REDIRECT_ODBC_API(SQLPutData,49)
// #pragma REDIRECT_ODBC_API(SQLRowCount,20)
// #pragma REDIRECT_ODBC_API(SQLSetConnectAttr,39)
// #pragma REDIRECT_ODBC_API(SQLSetConnectAttrA,239)
// #pragma REDIRECT_ODBC_API(SQLSetConnectAttrW,139)
// #pragma REDIRECT_ODBC_API(SQLSetConnectOption,50)
// #pragma REDIRECT_ODBC_API(SQLSetConnectOptionA,250)
// #pragma REDIRECT_ODBC_API(SQLSetConnectOptionW,150)
// #pragma REDIRECT_ODBC_API(SQLSetCursorName,21)
// #pragma REDIRECT_ODBC_API(SQLSetCursorNameA,221)
// #pragma REDIRECT_ODBC_API(SQLSetCursorNameW,121)
//#pragma REDIRECT_ODBC_API(SQLSetDescField,73)//ENTER_DESC
//#pragma REDIRECT_ODBC_API(SQLSetDescFieldA,273)//ENTER_DESC
//#pragma REDIRECT_ODBC_API(SQLSetDescFieldW,173)//ENTER_DESC
//#pragma REDIRECT_ODBC_API(SQLSetDescRec,74)//ENTER_DESC
//#pragma REDIRECT_ODBC_API(SQLSetEnvAttr,75)
// #pragma REDIRECT_ODBC_API(SQLSetParam,22)
// #pragma REDIRECT_ODBC_API(SQLSetPos,68)
// #pragma REDIRECT_ODBC_API(SQLSetScrollOptions,69)
// #pragma REDIRECT_ODBC_API(SQLSetStmtAttr,76)
// #pragma REDIRECT_ODBC_API(SQLSetStmtAttrA,276)
// #pragma REDIRECT_ODBC_API(SQLSetStmtAttrW,176)
// #pragma REDIRECT_ODBC_API(SQLSetStmtOption,51)
// #pragma REDIRECT_ODBC_API(SQLSpecialColumns,52)
// #pragma REDIRECT_ODBC_API(SQLSpecialColumnsA,252)
// #pragma REDIRECT_ODBC_API(SQLSpecialColumnsW,152)
// #pragma REDIRECT_ODBC_API(SQLStatistics,53)
// #pragma REDIRECT_ODBC_API(SQLStatisticsA,253)
// #pragma REDIRECT_ODBC_API(SQLStatisticsW,153)
// #pragma REDIRECT_ODBC_API(SQLTablePrivileges,70)
// #pragma REDIRECT_ODBC_API(SQLTablePrivilegesA,270)
// #pragma REDIRECT_ODBC_API(SQLTablePrivilegesW,170)
// #pragma REDIRECT_ODBC_API(SQLTables,54)
// #pragma REDIRECT_ODBC_API(SQLTablesA,254)
// #pragma REDIRECT_ODBC_API(SQLTablesW,154)
// #pragma REDIRECT_ODBC_API(SQLTransact,23)
