#ifndef SERIALIZE_FORMAT_H
#define SERIALIZE_FORMAT_H

#include <list>
#include <string>

/*
 * todo
 * XXX_SERIALIZE_FORMAT_C means compact format
 * XXX_SERIALIZE_FORMAT_B means beautify format
 *
 * */

/*
 * In XXX_SERIALIZE_FORMAT_C
 * FormatDetail has 2 types depend on is_simple,
 * if is_simple 1 then, it usually means a string literal(s0), key, s2 is ignored
 * if is_simple 0 then, it usually means a syntax node, key means the child index in it's parent, s0 means before (string literal), s1 means after (string literal)
 * */

/*
 * In XXX_SERIALIZE_FORMAT_B
 * Use '\n' in s0 or s1 to control beautify process (is_simple 0)
 * If is_simple 1 then '\n' only in s0.
 * */

struct FormatDetail
{
    char is_simple;
    const std::string s0;
    int key;
    const std::string s2;
};
typedef const std::list<FormatDetail> Form;
struct _FmCB {
    Form *compact_;
    Form *beautify_;
};
#define FmCB const _FmCB
/*----SQLSERVER-----*/
extern Form SP_EXECUTESQL_SERIALIZE_FORMAT_C;
extern FmCB SP_EXECUTESQL_SERIALIZE_FORMAT;

extern Form PIVOT_CLAUSE_SERIALIZE_FORMAT_C;
extern FmCB PIVOT_CLAUSE_SERIALIZE_FORMAT;

extern Form FUNC_TRIM_SERIALIZE_FORMAT_C;
extern FmCB FUNC_TRIM_SERIALIZE_FORMAT;

/*----BD2-----*/

extern Form DB2_TABLE_SERIALIZE_FORMAT_C;
extern FmCB DB2_TABLE_SERIALIZE_FORMAT;

/*----ORACLE---*/
extern Form FUN_EXTRACT_SERIALIZE_FORMAT_ORA_C;
extern FmCB FUN_EXTRACT_SERIALIZE_FORMAT_ORA;

extern Form STMT_BODYS_SERIALIZE_FORMAT_C;
extern FmCB STMT_BODYS_SERIALIZE_FORMAT_ORA;

extern Form RETURNING_INTO_SERIALIZE_FORMAT_C;
extern FmCB RETURNING_INTO_SERIALIZE_FORMAT;

extern Form FETCH_FIRST_ROW_ONLY_C;
extern FmCB FETCH_FIRST_ROW_SERIALIZE_FORMAT;
extern Form FETCH_FIRST_ROWS_ONLY_C;
extern FmCB FETCH_FIRST_ROWS_SERIALIZE_FORMAT;

extern Form COMMON_TABLE_EXPR_SERIALIZE_FORMAT_C_ORA;
//extern Form COMMON_TABLE_EXPR_SERIALIZE_FORMAT_B;
extern FmCB COMMON_TABLE_EXPR_SERIALIZE_FORMAT_ORA;

extern Form SEARCH_CLAUSE_SERIALIZE_FORMAT_C_ORA;
extern FmCB  SEARCH_CLAUSE_SERIALIZE_FORMAT_ORA;

extern Form  CYCLE_CLAUSE_SERIALIZE_FORMAT_C_ORA;
extern FmCB  CYCLE_CLAUSE_SERIALIZE_FORMAT_ORA;


extern Form SAMPLE_CLAUSE_SERIALIZE_FORMAT_C;
extern Form SAMPLE_CLAUSE_SERIALIZE_FORMAT_B;
extern FmCB SAMPLE_CLAUSE_SERIALIZE_FORMAT;
extern Form EORA_SEED_VALUE_SERIALIZE_FORMAT_C;
extern FmCB EORA_SEED_VALUE_SERIALIZE_FORMAT;
extern Form OFFSET_SERIALIZE_FORMAT_C;
extern FmCB OFFSET_SERIALIZE_FORMAT;

extern Form SELECT_SERIALIZE_FORMAT_ORA_C;
extern Form SELECT_SERIALIZE_FORMAT_ORA_B;
extern FmCB SELECT_SERIALIZE_FORMAT_ORA;

extern Form SELECT_SERIALIZE_FORMAT_ORA_C2;
extern Form SELECT_SERIALIZE_FORMAT_ORA_B2;
extern FmCB SELECT_SERIALIZE_FORMAT2_ORA;
extern Form PARTITION_BY_SERIALIZE_FORMAT_C;
extern FmCB PARTITION_BY_SERIALIZE_FORMAT;

extern Form ALTER_SESSION_SERIALIZE_FORMAT_C;
extern FmCB ALTER_SESSION_SERIALIZE_FORMAT_ORA;
/*----BIGQUERY----*/
extern Form EXPR_COMMA_SERIALIZE_FORMAT_C;
extern FmCB EXPR_COMMA_SERIALIZE_FORMAT;

extern Form UNNEST_DEF_SERIALIZE_FORMAT_C;
extern FmCB UNNEST_DEF_SERIALIZE_FORMAT;

extern Form STRUCT_TYPE_SERIALIZE_FORMAT_C;
extern FmCB STRUCT_TYPE_SERIALIZE_FORMAT;
extern Form ARRAY_TYPE_SERIALIZE_FORMAT_C;
extern FmCB ARRAY_TYPE_SERIALIZE_FORMAT;

extern Form MEMBER_DEF_SERIALIZE_FORMAT_C;
extern FmCB MEMBER_DEF_SERIALIZE_FORMAT;

extern Form ASTERISK_QUALIFY_SERIALIZE_FORMAT_C;
extern FmCB ASTERISK_QUALIFY_SERIALIZE_FORMAT;

extern Form EXCEPT_EXPR_SERIALIZE_FORMAT_C;
extern Form EXCEPT_EXPR_SERIALIZE_FORMAT_B;
extern FmCB EXCEPT_EXPR_SERIALIZE_FORMAT;

extern Form REPLACE_EXPR_SERIALIZE_FORMAT_C;
extern FmCB REPLACE_EXPR_SERIALIZE_FORMAT;

extern Form ROW_EXPR_AS_SERIALIZE_FORMAT_C;
extern FmCB ROW_EXPR_AS_SERIALIZE_FORMAT;



extern Form OFFSET_NUM_FORMAT_C;
extern FmCB OFFSET_NUM_FORMAT;
extern Form LIMIT_NUM_FORMAT_C;
extern FmCB LIMIT_NUM_FORMAT;
/*----COMMON----*/
extern Form SEMICOLON_LIST_SERIALIZE_FORMAT_C;
extern Form SEMICOLON_LIST_SERIALIZE_FORMAT_B;
extern FmCB SEMICOLON_LIST_SERIALIZE_FORMAT;

extern Form SPACE_LIST_SERIALIZE_FORMAT_C;
extern Form SPACE_LIST_SERIALIZE_FORMAT_B;
extern FmCB SPACE_LIST_SERIALIZE_FORMAT;

extern Form COMMA_LIST_SERIALIZE_FORMAT_C;
extern Form COMMA_LIST_SERIALIZE_FORMAT_B;
extern FmCB COMMA_LIST_SERIALIZE_FORMAT;

extern Form SELECT_SERIALIZE_FORMAT_C;
extern Form SELECT_SERIALIZE_FORMAT_B;
extern FmCB SELECT_SERIALIZE_FORMAT;


extern Form SELECT_DIRECT_SERIALIZE_FORMAT_C;
extern Form SELECT_DIRECT_SERIALIZE_FORMAT_B;
extern FmCB SELECT_DIRECT_SERIALIZE_FORMAT;


extern Form SINGLE_WITH_PARENS_SERIALIZE_FORMAT_C;
/* SINGLE_WITH_PARENS_SERIALIZE_FORMAT_B */
extern FmCB SINGLE_WITH_PARENS_SERIALIZE_FORMAT;

extern Form SINGLE_WITH_BRACKETS_SERIALIZE_FORMAT_C;
/* SINGLE_WITH_PARENS_SERIALIZE_FORMAT_B */
extern FmCB SINGLE_WITH_BRACKETS_SERIALIZE_FORMAT;

extern Form SELECT_UNION_SERIALIZE_FORMAT_C;
extern Form SELECT_UNION_SERIALIZE_FORMAT_B;
extern FmCB SELECT_UNION_SERIALIZE_FORMAT;

extern Form SELECT_INTERSECT_SERIALIZE_FORMAT_C;
extern Form SELECT_INTERSECT_SERIALIZE_FORMAT_B;
extern FmCB SELECT_INTERSECT_SERIALIZE_FORMAT;

extern Form SELECT_EXCEPT_SERIALIZE_FORMAT_C;
extern Form SELECT_EXCEPT_SERIALIZE_FORMAT_B;
extern FmCB SELECT_EXCEPT_SERIALIZE_FORMAT;

extern Form WHERE_SERIALIZE_FORMAT_C;
extern Form WHERE_SERIALIZE_FORMAT_B;
extern FmCB WHERE_SERIALIZE_FORMAT;

extern Form FROM_SERIALIZE_FORMAT_C;
extern Form FROM_SERIALIZE_FORMAT_B;
extern FmCB FROM_SERIALIZE_FORMAT;

extern Form GROUP_BY_SERIALIZE_FORMAT_C;
/* GROUP_BY_SERIALIZE_FORMAT_B */
extern FmCB GROUP_BY_SERIALIZE_FORMAT;

extern Form ORDER_BY_SERIALIZE_FORMAT_C;
/* ORDER_BY_SERIALIZE_FORMAT_B */
extern FmCB ORDER_BY_SERIALIZE_FORMAT;
extern Form ORDER_SIBLINGS_BY_SERIALIZE_FORMAT_C;
/* ORDER_BY_SERIALIZE_FORMAT_B */
extern FmCB ORDER_SIBLINGS_BY_SERIALIZE_FORMAT;

extern Form SORT_KEY_SERIALIZE_FORMAT_C;
/* SORT_KEY_SERIALIZE_FORMAT_B */
extern FmCB SORT_KEY_SERIALIZE_FORMAT;


extern Form HAVING_SERIALIZE_FORMAT_C;
/* HAVING_SERIALIZE_FORMAT_B */
extern FmCB HAVING_SERIALIZE_FORMAT;

/*----------------------------------------------------------------------------------------------------------------------------------------------*/
extern Form SINGLE_SERIALIZE_FORMAT_C;
/* SINGLE_SERIALIZE_FORMAT_B */
extern FmCB SINGLE_SERIALIZE_FORMAT;
extern Form DOUBLE_SERIALIZE_FORMAT_C;
/* DOUBLE_SERIALIZE_FORMAT_B */
extern FmCB DOUBLE_SERIALIZE_FORMAT;
extern Form TRIPLE_SERIALIZE_FORMAT_C;
extern FmCB TRIPLE_SERIALIZE_FORMAT;
/*
 * ORACLE only support table alias without keyword AS
 * But, opt AS is supported by most DBMS.
 * */
extern Form AS_LABEL_SERIALIZE_FORMAT_C;
extern FmCB AS_LABEL_SERIALIZE_FORMAT;

extern Form AS_SERIALIZE_FORMAT_C;
/* AS_SERIALIZE_FORMAT_B */
extern FmCB AS_SERIALIZE_FORMAT;

extern Form ORA_AS_SERIALIZE_FORMAT_C;
/* ORA_AS_SERIALIZE_FORMAT_B */
extern FmCB ORA_AS_SERIALIZE_FORMAT;


extern Form QUADRUPLE_SERIALIZE_FORMAT_C;
/* QUADRUPLE_SERIALIZE_FORMAT_B */
extern FmCB QUADRUPLE_SERIALIZE_FORMAT;

extern Form PENTA_SERIALIZE_FORMAT_C;
/* PENTA_SERIALIZE_FORMAT_C */
extern FmCB PENTA_SERIALIZE_FORMAT;

extern Form PENTA_SERIALIZE_FORMAT_0_C;
/* PENTA_SERIALIZE_FORMAT_0_B */
extern FmCB PENTA_SERIALIZE_FORMAT_0;

extern Form JOINED_TB_1_SERIALIZE_FORMAT_C;
extern Form JOINED_TB_1_SERIALIZE_FORMAT_B;
extern FmCB JOINED_TB_1_SERIALIZE_FORMAT;


extern Form JOINED_TB_USING_SERIALIZE_FORMAT_C;
extern Form JOINED_TB_USING_SERIALIZE_FORMAT_B;
extern FmCB JOINED_TB_USING_SERIALIZE_FORMAT;

extern Form JOINED_TB_2_SERIALIZE_FORMAT_C;
extern Form JOINED_TB_2_SERIALIZE_FORMAT_B;
extern FmCB JOINED_TB_2_SERIALIZE_FORMAT;

extern Form JOINED_TB_3_SERIALIZE_FORMAT_C;
extern Form JOINED_TB_3_SERIALIZE_FORMAT_B;
extern FmCB JOINED_TB_3_SERIALIZE_FORMAT;

extern Form OP_EXISTS_SERIALIZE_FORMAT_C;
/* OP_EXISTS_SERIALIZE_FORMAT_B */
extern FmCB OP_EXISTS_SERIALIZE_FORMAT;

extern Form OP_POS_SERIALIZE_FORMAT_C;
/* OP_POS_SERIALIZE_FORMAT_B */
extern FmCB OP_POS_SERIALIZE_FORMAT;

extern Form OP_NEG_SERIALIZE_FORMAT_C;
/* OP_NEG_SERIALIZE_FORMAT_B */
extern FmCB OP_NEG_SERIALIZE_FORMAT;

extern Form OP_ADD_SERIALIZE_FORMAT_C;
/* OP_ADD_SERIALIZE_FORMAT_B */
extern FmCB OP_ADD_SERIALIZE_FORMAT;

extern Form OP_MINUS_SERIALIZE_FORMAT_C;
/* OP_MINUS_SERIALIZE_FORMAT_B */
extern FmCB OP_MINUS_SERIALIZE_FORMAT;

extern Form OP_MUL_SERIALIZE_FORMAT_C;
/* OP_MUL_SERIALIZE_FORMAT_B */
extern FmCB OP_MUL_SERIALIZE_FORMAT;

extern Form OP_DIV_SERIALIZE_FORMAT_C;
/* OP_DIV_SERIALIZE_FORMAT_C */
extern FmCB OP_DIV_SERIALIZE_FORMAT;

extern Form OP_REM_SERIALIZE_FORMAT_C;
/* OP_REM_SERIALIZE_FORMAT_B */
extern FmCB OP_REM_SERIALIZE_FORMAT;

extern Form OP_POW_SERIALIZE_FORMAT_C;
/* OP_POW_SERIALIZE_FORMAT_C */
extern FmCB OP_POW_SERIALIZE_FORMAT;

extern Form OP_MOD_SERIALIZE_FORMAT_C;
/* OP_MOD_SERIALIZE_FORMAT_B */
extern FmCB OP_MOD_SERIALIZE_FORMAT;

extern Form OP_LE_SERIALIZE_FORMAT_C;
/* OP_LE_SERIALIZE_FORMAT_B */
extern FmCB OP_LE_SERIALIZE_FORMAT;

extern Form OP_LT_SERIALIZE_FORMAT_C;
/* OP_LT_SERIALIZE_FORMAT_B */
extern FmCB OP_LT_SERIALIZE_FORMAT;

extern Form OP_EQ_SERIALIZE_FORMAT_C;
/* OP_EQ_SERIALIZE_FORMAT_B */
extern FmCB OP_EQ_SERIALIZE_FORMAT;

extern Form OP_GE_SERIALIZE_FORMAT_C;
/* OP_GE_SERIALIZE_FORMAT_B */
extern FmCB OP_GE_SERIALIZE_FORMAT;

extern Form OP_GT_SERIALIZE_FORMAT_C;
/* OP_GT_SERIALIZE_FORMAT_B */
extern FmCB OP_GT_SERIALIZE_FORMAT;

extern Form OP_NE_SERIALIZE_FORMAT_C;
/* OP_NE_SERIALIZE_FORMAT_B */
extern FmCB OP_NE_SERIALIZE_FORMAT;

extern Form OP_LE_ALL_SERIALIZE_FORMAT_C;
/* OP_LE_ALL_SERIALIZE_FORMAT_C */
extern FmCB OP_LE_ALL_SERIALIZE_FORMAT;

extern Form OP_LT_ALL_SERIALIZE_FORMAT_C;
/* OP_LT_ALL_SERIALIZE_FORMAT_B */
extern FmCB OP_LT_ALL_SERIALIZE_FORMAT;

extern Form OP_EQ_ALL_SERIALIZE_FORMAT_C;
/* OP_EQ_ALL_SERIALIZE_FORMAT_B */
extern FmCB OP_EQ_ALL_SERIALIZE_FORMAT;

extern Form OP_GE_ALL_SERIALIZE_FORMAT_C;
/* OP_GE_ALL_SERIALIZE_FORMAT_B */
extern FmCB OP_GE_ALL_SERIALIZE_FORMAT;

extern Form OP_GT_ALL_SERIALIZE_FORMAT_C;
/* OP_GT_ALL_SERIALIZE_FORMAT_B */
extern FmCB OP_GT_ALL_SERIALIZE_FORMAT;

extern Form OP_NE_ALL_SERIALIZE_FORMAT_C;
/* OP_NE_ALL_SERIALIZE_FORMAT_B */
extern FmCB OP_NE_ALL_SERIALIZE_FORMAT;

extern Form OP_LE_SOME_SERIALIZE_FORMAT_C;
/* OP_LE_SOME_SERIALIZE_FORMAT_B */
extern FmCB OP_LE_SOME_SERIALIZE_FORMAT;

extern Form OP_LT_SOME_SERIALIZE_FORMAT_C;
/* OP_LT_SOME_SERIALIZE_FORMAT_B */
extern FmCB OP_LT_SOME_SERIALIZE_FORMAT;

extern Form OP_EQ_SOME_SERIALIZE_FORMAT_C;
/* OP_EQ_SOME_SERIALIZE_FORMAT_B */
extern FmCB OP_EQ_SOME_SERIALIZE_FORMAT;

extern Form OP_GE_SOME_SERIALIZE_FORMAT_C;
/* OP_GE_SOME_SERIALIZE_FORMAT_B */
extern FmCB OP_GE_SOME_SERIALIZE_FORMAT;

extern Form OP_GT_SOME_SERIALIZE_FORMAT_C;
/* OP_GT_SOME_SERIALIZE_FORMAT_B */
extern FmCB OP_GT_SOME_SERIALIZE_FORMAT;

extern Form OP_NE_SOME_SERIALIZE_FORMAT_C;
/* OP_NE_SOME_SERIALIZE_FORMAT_B */
extern FmCB OP_NE_SOME_SERIALIZE_FORMAT;

extern Form OP_LE_ANY_SERIALIZE_FORMAT_C;
/* OP_LE_ANY_SERIALIZE_FORMAT_B */
extern FmCB OP_LE_ANY_SERIALIZE_FORMAT;

extern Form OP_LT_ANY_SERIALIZE_FORMAT_C;
/* OP_LT_ANY_SERIALIZE_FORMAT_B */
extern FmCB OP_LT_ANY_SERIALIZE_FORMAT;

extern Form OP_EQ_ANY_SERIALIZE_FORMAT_C;
/* OP_EQ_ANY_SERIALIZE_FORMAT_C */
extern FmCB OP_EQ_ANY_SERIALIZE_FORMAT;

extern Form OP_GE_ANY_SERIALIZE_FORMAT_C;
/* OP_GE_ANY_SERIALIZE_FORMAT_B */
extern FmCB OP_GE_ANY_SERIALIZE_FORMAT;

extern Form OP_GT_ANY_SERIALIZE_FORMAT_C;
/* OP_GT_ANY_SERIALIZE_FORMAT_B */
extern FmCB OP_GT_ANY_SERIALIZE_FORMAT;

extern Form OP_NE_ANY_SERIALIZE_FORMAT_C;
/* OP_NE_ANY_SERIALIZE_FORMAT_B */
extern FmCB OP_NE_ANY_SERIALIZE_FORMAT;

extern Form OP_LIKE_SERIALIZE_FORMAT_C;
/* OP_LIKE_SERIALIZE_FORMAT_B */
extern FmCB OP_LIKE_SERIALIZE_FORMAT;

extern Form OP_NOT_LIKE_SERIALIZE_FORMAT_C;
/* OP_NOT_LIKE_SERIALIZE_FORMAT_B */
extern FmCB OP_NOT_LIKE_SERIALIZE_FORMAT;

extern Form OP_AND_SERIALIZE_FORMAT_C;
extern Form OP_AND_SERIALIZE_FORMAT_B;
extern FmCB OP_AND_SERIALIZE_FORMAT;

extern Form OP_OR_SERIALIZE_FORMAT_C;
extern Form OP_OR_SERIALIZE_FORMAT_B;
extern FmCB OP_OR_SERIALIZE_FORMAT;

extern Form OP_NOT_SERIALIZE_FORMAT_C;
/* OP_NOT_SERIALIZE_FORMAT_B */
extern FmCB OP_NOT_SERIALIZE_FORMAT;

extern Form OP_IS_SERIALIZE_FORMAT_C;
/* OP_IS_SERIALIZE_FORMAT_B */
extern FmCB OP_IS_SERIALIZE_FORMAT;

extern Form OP_IS_NOT_SERIALIZE_FORMAT_C;
/* OP_IS_NOT_SERIALIZE_FORMAT */
extern FmCB OP_IS_NOT_SERIALIZE_FORMAT;

extern Form OP_BETWEEN_SERIALIZE_FORMAT_C;
/* OP_BETWEEN_SERIALIZE_FORMAT_B */
extern FmCB OP_BETWEEN_SERIALIZE_FORMAT;

extern Form OP_NOT_BETWEEN_SERIALIZE_FORMAT_C;
/* OP_NOT_BETWEEN_SERIALIZE_FORMAT_B */
extern FmCB OP_NOT_BETWEEN_SERIALIZE_FORMAT;

extern Form OP_IN_SERIALIZE_FORMAT_C;
/* OP_IN_SERIALIZE_FORMAT_B */
extern FmCB OP_IN_SERIALIZE_FORMAT;

extern Form OP_NOT_IN_SERIALIZE_FORMAT_C;
/* OP_NOT_IN_SERIALIZE_FORMAT_B */
extern FmCB OP_NOT_IN_SERIALIZE_FORMAT;

extern Form OP_CNN_SERIALIZE_FORMAT_C;
/* OP_CNN_SERIALIZE_FORMAT_B */
extern FmCB OP_CNN_SERIALIZE_FORMAT;

//E_BIT_OP_AND,// &//E_BIT_OP_OR, // |//E_BIT_OP_NOT,// ~//E_BIT_OP_LS,// <<//E_BIT_OP_RS, >>
extern Form OP_BIT_LS_SERIALIZE_FORMAT_C;
extern FmCB OP_BIT_LS_SERIALIZE_FORMAT;
extern Form OP_BIT_RS_SERIALIZE_FORMAT_C;
extern FmCB OP_BIT_RS_SERIALIZE_FORMAT;
extern Form OP_BIT_AND_SERIALIZE_FORMAT_C;
extern FmCB OP_BIT_AND_SERIALIZE_FORMAT;
extern Form OP_BIT_OR_SERIALIZE_FORMAT_C;
extern FmCB OP_BIT_OR_SERIALIZE_FORMAT;
extern Form OP_BIT_NOT_SERIALIZE_FORMAT_C;
extern FmCB OP_BIT_NOT_SERIALIZE_FORMAT;


extern Form CASE_SERIALIZE_FORMAT_C;
extern Form CASE_SERIALIZE_FORMAT_B;
extern FmCB CASE_SERIALIZE_FORMAT;

extern Form WHEN_SERIALIZE_FORMAT_C;
/* WHEN_SERIALIZE_FORMAT_B */
extern FmCB WHEN_SERIALIZE_FORMAT;

extern Form ELSE_SERIALIZE_FORMAT_C;
/* ELSE_SERIALIZE_FORMAT_B */
extern FmCB ELSE_SERIALIZE_FORMAT;

extern Form FUN_CALL_1_OVER_SERIALIZE_FORMAT_C;
/* FUN_CALL_1_OVER_SERIALIZE_FORMAT_B */
extern FmCB FUN_CALL_1_OVER_SERIALIZE_FORMAT;

extern Form FUN_CALL_DIS_OVER_SERIALIZE_FORMAT_C;
/* FUN_CALL_DIS_OVER_SERIALIZE_FORMAT_B */
extern FmCB FUN_CALL_DIS_OVER_SERIALIZE_FORMAT;

extern Form FUN_CALL_BIGQUERY_S_FORMAT_C;
/* FUN_CALL_BIGQUERY_SERIALIZE_FORMAT_B */
extern FmCB FUN_CALL_BIGQUERY_S_FORMAT;


extern Form FUN_CALL_AS_SERIALIZE_FORMAT_C;
/* FUN_CALL_AS_SERIALIZE_FORMAT_B */
extern FmCB FUN_CALL_AS_SERIALIZE_FORMAT;

extern Form FUN_CALL_USING_SERIALIZE_FORMAT_C;
/* FUN_CALL_USING_SERIALIZE_FORMAT_B */
extern FmCB FUN_CALL_USING_SERIALIZE_FORMAT;

extern Form WITH_CLAUSE_SERIALIZE_FORMAT_C;
/* WITH_CLAUSE_SERIALIZE_FORMAT_B */
extern FmCB WITH_CLAUSE_SERIALIZE_FORMAT;

extern Form WITH_RECURSIVE_CLAUSE_SERIALIZE_FORMAT_C;
/* WITH_RECURSIVE_CLAUSE_SERIALIZE_FORMAT_B */
extern FmCB WITH_RECURSIVE_CLAUSE_SERIALIZE_FORMAT;

extern Form COMMON_TABLE_EXPR_SERIALIZE_FORMAT_C;
//extern Form COMMON_TABLE_EXPR_SERIALIZE_FORMAT_B;
extern FmCB COMMON_TABLE_EXPR_SERIALIZE_FORMAT;


extern Form TABLE_IDENT_SERIALIZE_FORMAT_1_C;
/* TABLE_IDENT_SERIALIZE_FORMAT_1_B */
extern FmCB TABLE_IDENT_SERIALIZE_FORMAT_1;

extern Form TABLE_IDENT_SERIALIZE_FORMAT_2_C;
/* TABLE_IDENT_SERIALIZE_FORMAT_2_B */
extern FmCB TABLE_IDENT_SERIALIZE_FORMAT_2;

extern Form TABLE_IDENT_SERIALIZE_FORMAT_3_C;
/* TABLE_IDENT_SERIALIZE_FORMAT_3_B */
extern FmCB TABLE_IDENT_SERIALIZE_FORMAT_3;
//
//extern Form OP_NAME_FIELD_SERIALIZE_FORMAT_1_C;
///* OP_NAME_FIELD_SERIALIZE_FORMAT_1_B */
//extern FmCB OP_NAME_FIELD_SERIALIZE_FORMAT_1;
//
//extern Form OP_NAME_FIELD_SERIALIZE_FORMAT_2_C;
///* OP_NAME_FIELD_SERIALIZE_FORMAT_2_B */
//extern FmCB OP_NAME_FIELD_SERIALIZE_FORMAT_2;
//
//extern Form OP_NAME_FIELD_SERIALIZE_FORMAT_3_C;
///* OP_NAME_FIELD_SERIALIZE_FORMAT_3_B */
//extern FmCB OP_NAME_FIELD_SERIALIZE_FORMAT_3;

extern Form OP_NAME_FIELD_SERIALIZE_FORMAT_4_C;
/* OP_NAME_FIELD_SERIALIZE_FORMAT_4_B */
extern FmCB OP_NAME_FIELD_SERIALIZE_FORMAT_4;

extern Form OVER_CLAUSE_SERIALIZE_FORMAT_C;
/* OVER_CLAUSE_SERIALIZE_FORMAT_B */
extern FmCB OVER_CLAUSE_SERIALIZE_FORMAT;

extern Form WINDOW_SPECIFIC_CLAUSE_SERIALIZE_FORMAT_C;
/* WINDOW_SPECIFIC_CLAUSE_SERIALIZE_FORMAT_B */
extern FmCB WINDOW_SPECIFIC_CLAUSE_SERIALIZE_FORMAT;

extern Form TABLE_VALUE_CTOR_SERIALIZE_FORMAT_C;
/* TABLE_VALUE_CTOR_SERIALIZE_FORMAT_B */
extern FmCB TABLE_VALUE_CTOR_SERIALIZE_FORMAT;

extern Form CREATE_TABLE_SERIALIZE_FORMAT_C;
extern FmCB CREATE_TABLE_SERIALIZE_FORMAT;

extern Form DROP_TABLE_SERIALIZE_FORMAT_C;
extern Form DROP_TABLE_SERIALIZE_FORMAT_B;
extern FmCB DROP_TABLE_SERIALIZE_FORMAT;

extern Form UPDATE_SERIALIZE_FORMAT_C;
extern Form UPDATE_SERIALIZE_FORMAT_B;
extern FmCB UPDATE_SERIALIZE_FORMAT;

extern Form DELETE_SERIALIZE_FORMAT_C;
extern Form DELETE_SERIALIZE_FORMAT_B;
extern FmCB DELETE_SERIALIZE_FORMAT;

extern Form DELETE_SERIALIZE_FORMAT_V2_C;
extern Form DELETE_SERIALIZE_FORMAT_V2_B;
extern FmCB DELETE_SERIALIZE_FORMAT_V2;

extern Form INSERT_SERIALIZE_FORMAT_C;
extern Form INSERT_SERIALIZE_FORMAT_B;
extern FmCB INSERT_SERIALIZE_FORMAT;
extern Form INSERT_SERIALIZE_FORMAT_V2_C;
extern Form INSERT_SERIALIZE_FORMAT_V2_B;
extern FmCB INSERT_SERIALIZE_FORMAT_V2;
extern Form INSERT_SERIALIZE_FORMAT_V3_C;
extern Form INSERT_SERIALIZE_FORMAT_V3_B;
extern FmCB INSERT_SERIALIZE_FORMAT_V3;

extern Form CALL_SERIALIZE_FORMAT_C;
/* CALL_SERIALIZE_FORMAT_B */
extern FmCB CALL_SERIALIZE_FORMAT;

extern Form CALL_SQL_SERVER_SERIALIZE_FORMAT_C;
/* CALL_SQL_SERVER_SERIALIZE_FORMAT_B */
extern FmCB CALL_SQL_SERVER_SERIALIZE_FORMAT;

extern Form CALL_HANA_SERIALIZE_FORMAT_C;
/* CALL_SQL_SERVER_SERIALIZE_FORMAT_B */
extern FmCB CALL_HANA_SERIALIZE_FORMAT;

extern Form CALL_HANA_SERIALIZE_FORMAT2_C;
/* CALL_SQL_SERVER_SERIALIZE_FORMAT_B */
extern FmCB CALL_HANA_SERIALIZE_FORMAT2;

extern Form SQL_ARGUMENT_SERIALIZE_FORMAT_C;
/* SQL_ARGUMENT_SERIALIZE_FORMAT_B */
extern FmCB SQL_ARGUMENT_SERIALIZE_FORMAT;

extern Form USE_SERIALIZE_FORMAT_C;
extern FmCB USE_SERIALIZE_FORMAT;



/*--------HANA----------*/

extern Form OPTION_STRING_FORMAT_C;
extern FmCB OPTION_STRING_FORMAT;
extern Form RETURNS_CLAUSE_FORMAT_C;
extern FmCB RETURNS_CLAUSE_FORMAT;
extern Form FOR_CLAUSE_FORMAT_C;
extern FmCB FOR_CLAUSE_FORMAT;

extern Form WITHIN_GROUP_SF;
extern FmCB WITHIN_GROUP_SERIALIZE_FORMAT;

extern Form TIME_TRAVEL_FORMAT_C;
extern FmCB TIME_TRAVEL_FORMAT;

extern Form TABLE_VAR_SF;
extern FmCB TABLE_VAR_SERIALIZE_FORMAT;
extern Form ASSOCIATED_TAB_SF;//relation_factor '[' opt_search_condition ']' ':' associated_ref_list
extern FmCB ASSOCIATED_TAB_SERIALIZE_FORMAT;
extern Form ASSOCIATED_LIST_SF;
extern FmCB ASSOCIATED_LIST_SERIALIZE_FORMAT;
extern Form ASSOCIATED_REF_SF;//relation_factor '[' opt_search_condition opt_many2one_part ']'
extern FmCB ASSOCIATED_REF_SERIALIZE_FORMAT;


extern Form LATERAL_QUERY_SERIALIZE_FORMAT_C;
extern FmCB LATERAL_QUERY_SERIALIZE_FORMAT;

extern Form CASE_JOIN_RET_SF_C;//RETURN select_expr_list_parens FROM table_reference ON search_condition
extern FmCB CASE_JOIN_RET_SERIALIZE_FORMAT;
extern Form CASE_JOIN_WHEN_SF_C;//WHEN search_condition THEN ret_join_on
extern FmCB CASE_JOIN_WHEN_SERIALIZE_FORMAT;
extern Form CASE_JOIN_ELSE_SF_C;//ELSE ret_join_on
extern FmCB CASE_JOIN_ELSE_SERIALIZE_FORMAT;
extern Form CASE_JOIN_SF_C;//CASE JOIN  case_join_when_list opt_case_join_else  END
extern FmCB CASE_JOIN_SERIALIZE_FORMAT;

extern Form POINT_VALUE_FORMAT_C;
extern FmCB POINT_VALUE_FORMAT;

extern Form UNNEST_TABLE_FORMAT_C;
extern FmCB UNNEST_TABLE_FORMAT;
extern Form COLLECT_VAL_FORMAT_C;
extern FmCB COLLECT_VAL_FORMAT;
extern Form AS_DERIVED_PART_FORMAT_C;
extern FmCB AS_DERIVED_PART_FORMAT;

extern Form AGG_ORDER_SERIALIZE_FORMAT_C;
extern FmCB AGG_ORDER_SERIALIZE_FORMAT;

extern Form REPLACE_SERIALIZE_FORMAT_C;
extern Form REPLACE_SERIALIZE_FORMAT_B;
extern FmCB REPLACE_SERIALIZE_FORMAT;
extern Form UPSERT_SERIALIZE_FORMAT_C;
extern Form UPSERT_SERIALIZE_FORMAT_B;
extern FmCB UPSERT_SERIALIZE_FORMAT;

// select ...from  ...  ? AS "t_00" ("C_0" NVARCHAR(3), "C_1" NVARCHAR(25), "C_2" NVARCHAR(2), "C_3" NVARCHAR(3))
extern Form CONSTRUCT_FROM_TABLE_C;
extern Form CONSTRUCT_FROM_TABLE_B;
extern FmCB CONSTRUCT_FROM_TABLE_SERIALIZE_FORMAT;

extern Form CONSTRUCT_COL_C;
extern Form CONSTRUCT_COL_B;
extern FmCB CONSTRUCT_COL_SERIALIZE_FORMAT;

extern Form HINT_CLAUSE_FORMAT_C;
extern Form HINT_CLAUSE_FORMAT_B;
extern FmCB HINT_CLAUSE_FORMAT;

extern Form FOR_UPDATE_FORMAT_C;
extern Form FOR_UPDATE_FORMAT_B;
extern FmCB FOR_UPDATE_FORMAT;

extern Form FOR_UPDATE_FORMAT_HANA_B;
extern FmCB FOR_UPDATE_FORMAT_HANA;

extern Form WAIT_TIME_FORMAT_C;
extern Form WAIT_TIME_FORMAT_B;
extern FmCB WAIT_TIME_FORMAT;

extern Form TOP_CLAUSE_FORMAT_C;
extern Form TOP_CLAUSE_FORMAT_B;
extern FmCB TOP_CLAUSE_FORMAT;

extern Form LIMIT_NUM_FORMAT_HANA_B;
extern FmCB LIMIT_NUM_FORMAT_HANA;



extern Form SELECT_DIRECT_SERIALIZE_FORMAT_HANA_C;
extern Form SELECT_DIRECT_SERIALIZE_FORMAT_HANA_B;
extern FmCB SELECT_DIRECT_SERIALIZE_FORMAT_HANA;


extern Form SELECT_EXCEPT_SERIALIZE_FORMAT_HANA_C;
extern Form SELECT_EXCEPT_SERIALIZE_FORMAT_HANA_B;
extern FmCB SELECT_EXCEPT_SERIALIZE_FORMAT_HANA;


extern Form OP_MEMBER_SERIALIZE_FORMAT_C;
extern Form OP_NOT_MEMBER_SERIALIZE_FORMAT_C;
extern FmCB OP_MEMBER_SERIALIZE_FORMAT;
extern FmCB OP_NOT_MEMBER_SERIALIZE_FORMAT;

extern Form OP_LIKE_REGEXPR_SERIALIZE_FORMAT_C;
extern FmCB OP_LIKE_REGEXPR_SERIALIZE_FORMAT;

extern Form OP_AND_SPC_SERIALIZE_FORMAT_C;
extern FmCB OP_AND_SPC_SERIALIZE_FORMAT;

extern Form FUN_CALL_314_SERIALIZE_FORMAT_C;
/* FUN_CALL_DIS_OVER_SERIALIZE_FORMAT_B */
extern FmCB FUN_CALL_314_SERIALIZE_FORMAT;

//extern Form OP_NAME_FIELD_SERIALIZE_FORMAT_4_C;
//extern FmCB OP_NAME_FIELD_SERIALIZE_FORMAT_4;


extern Form DELETE_S_FORMAT_C2;
extern Form DELETE_S_FORMAT_B2;
extern FmCB DELETE_S_FORMAT;

extern Form SET_S_FORMAT_C;
extern FmCB SET_S_FORMAT_HANA;






#endif
