/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nextlabs_EMDB_EMDBSdk */

#ifndef _Included_com_nextlabs_EMDB_EMDBSdk
#define _Included_com_nextlabs_EMDB_EMDBSdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nextlabs_EMDB_EMDBSdk
 * Method:    EMDBInit_
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_nextlabs_EMDB_EMDBSdk_EMDBInit_1
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_nextlabs_EMDB_EMDBSdk
 * Method:    EMDBNewUserCtx_
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_nextlabs_EMDB_EMDBSdk_EMDBNewUserCtx_1
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_nextlabs_EMDB_EMDBSdk
 * Method:    EMDBFreeUserCtx_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nextlabs_EMDB_EMDBSdk_EMDBFreeUserCtx_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nextlabs_EMDB_EMDBSdk
 * Method:    EMDBSetUserCtxProperty_
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_nextlabs_EMDB_EMDBSdk_EMDBSetUserCtxProperty_1
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_nextlabs_EMDB_EMDBSdk
 * Method:    EMDBClearUserCtxProperty_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nextlabs_EMDB_EMDBSdk_EMDBClearUserCtxProperty_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nextlabs_EMDB_EMDBSdk
 * Method:    EMDBEvalSql_
 * Signature: (Ljava/lang/String;JLcom/nextlabs/EMDB/EMDBSdk/EMDBResult;)I
 */
JNIEXPORT jint JNICALL Java_com_nextlabs_EMDB_EMDBSdk_EMDBEvalSql_1
  (JNIEnv *, jclass, jstring, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
